server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/workflowdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Tokyo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  type-aliases-package: com.wf.**.model.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

